services:
  db:
    image: mysql:8.0
    container_name: pizzeria_db_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: pizzeria_db
    ports:
      - '3306:3306'
    volumes:
      - pizzeria_data:/var/lib/mysql

volumes:
  pizzeria_data:
